import test from 'node:test';import assert from 'node:assert/strict';import {createPaperBroker,preflight} from '../lib/broker.mjs';
const credentials={APCA_API_KEY_ID:'test-key',APCA_API_SECRET_KEY:'test-secret',APCA_API_BASE_URL:'https://api.alpaca.markets'};
const now=Date.parse('2026-09-09T15:00:00Z');const valid={symbol:'SPY',now,account:{status:'ACTIVE',currency:'USD',equity:'100',cash:'100',non_marginable_buying_power:'100'},clock:{is_open:true,timestamp:new Date(now).toISOString()},positions:[],orders:[],asset:{status:'active',tradable:true,fractionable:true},bar:{c:100,t:new Date(now-60000).toISOString()}};
test('adapter hardcodes paper host, rejects redirects and never follows a live override',async()=>{let call;const b=createPaperBroker(credentials,async(...args)=>{call=args;return Response.json({status:'ACTIVE'});});await b.account();assert.equal(call[0],'https://paper-api.alpaca.markets/v2/account');assert.equal(call[1].redirect,'error');assert.equal(call[1].headers['APCA-API-KEY-ID'],'test-key');});
test('missing credentials fail without network access',async()=>{let called=false;const b=createPaperBroker({},async()=>{called=true;});assert.equal(b.configured,false);await assert.rejects(b.account());assert.equal(called,false);});
test('invalid buys, oversized orders, unknown assets, live-like order types rejected',()=>{const b=createPaperBroker(credentials,()=>{throw Error('Must never call fetch');});const order={symbol:'SPY',side:'buy',type:'market',time_in_force:'day',extended_hours:false,client_order_id:'sterling-test',notional:'5.00'};for(const diff of [{notional:'6'},{notional:'NaN'},{notional:'0'},{symbol:'TSLA'},{extended_hours:true},{type:'limit'},{qty:'5'},{client_order_id:'bad'}])assert.throws(()=>b.submit({...order,...diff}));});
test('valid paper order and reconciliation preserve exact client ID',async()=>{let call;const b=createPaperBroker(credentials,async(...a)=>{call=a;return Response.json({id:'order1',status:'accepted'});});await b.submit({symbol:'SPY',side:'buy',type:'market',time_in_force:'day',extended_hours:false,client_order_id:'sterling-test',notional:'5.00'});assert.equal(call[0],'https://paper-api.alpaca.markets/v2/orders');assert.equal(JSON.parse(call[1].body).notional,'5.00');await b.findOrder('sterling-test');assert.ok(call[0].includes('client_order_id=sterling-test'));});
test('preflight handles valid cash account and rejects stale data, blocked account and pending orders',()=>{assert.equal(preflight(valid).cash,100);const bad=[{account:{...valid.account,cash:'NaN'}},{account:{...valid.account,currency:'GBP'}},{account:{...valid.account,trading_blocked:true}},{clock:{...valid.clock,is_open:false}},{bar:{...valid.bar,t:new Date(now-181000).toISOString()}},{bar:{...valid.bar,c:NaN}},{bar:{...valid.bar,t:'invalid'}},{orders:[{symbol:'SPY'}]},{positions:[{symbol:'AAPL',side:'long',qty:'1'}]},{asset:{...valid.asset,fractionable:false}}];for(const d of bad)assert.throws(()=>preflight({...valid,...d}));});
test('upstream failure messages do not leak keys or raw broker bodies',async()=>{const b=createPaperBroker(credentials,async()=>new Response('test-secret',{status:403}));await assert.rejects(b.account(),e=>!e.message.includes('test-secret')&&e.message.includes('403'));});
