import test from 'node:test';import assert from 'node:assert/strict';
import {paperStep} from '../lib/paper-session.mjs';import {demoBars} from '../lib/engine.mjs';
const now=Date.parse('2026-09-09T15:00:00Z');
function fixture(){let posts=0,saves=0;const state={version:1,accountId:null,configuration:null,pending:null,days:{},journal:[]};
 const bars=demoBars().slice(0,200);let d=new Date('2025-12-03T00:00:00Z');bars.forEach(b=>{b.date=d.toISOString().slice(0,10);b.open=100;b.high=101;b.low=99;b.close=100;d.setUTCDate(d.getUTCDate()+1);});bars.at(-1).date='2026-09-08';
 const broker={account:async()=>({id:'paper-account',status:'ACTIVE',currency:'USD',equity:'100',cash:'100',non_marginable_buying_power:'100'}),clock:async()=>({is_open:true,timestamp:new Date(now).toISOString()}),positions:async()=>[],orders:async()=>[],asset:async()=>({status:'active',tradable:true,fractionable:true}),latest:async()=>({c:100,t:new Date(now-60000).toISOString()}),bars:async()=>bars,findOrder:async()=>null,submit:async order=>{posts++;assert.ok(state.pending);assert.ok(saves>0);return {id:'paper-order',status:'accepted'};}};
 return {broker,state,save:async()=>{saves++;},enabled:true,strategy:'hold',symbol:'SPY',now,posts:()=>posts};}
test('dry run never submits a candidate',async()=>{const f=fixture();await paperStep({...f,enabled:false});assert.equal(f.posts(),0);assert.equal(f.state.pending,null);});
test('intent is persisted before submission and a restart with unknown outcome never resubmits',async()=>{const f=fixture();await paperStep(f);assert.equal(f.posts(),1);assert.equal(f.state.pending.notional,'5.00');await assert.rejects(paperStep(f),/unknown outcome/);assert.equal(f.posts(),1);});
test('timeout after submission leaves durable pending intent',async()=>{const f=fixture();let submitted=0;f.broker.submit=async()=>{submitted++;throw Error('timeout');};await assert.rejects(paperStep(f),/timeout/);assert.ok(f.state.pending);await assert.rejects(paperStep(f),/unknown outcome/);assert.equal(submitted,1);});
test('confirmed fill reconciles and next tick cannot repeat a daily action',async()=>{const f=fixture();await paperStep(f);f.broker.findOrder=async()=>({id:'paper-order',status:'filled',filled_qty:'.05'});await paperStep(f);assert.equal(f.state.pending,null);await paperStep(f);assert.equal(f.posts(),1);});
test('account switch, large default balance and pending orders cannot bypass controls',async()=>{for(const variant of ['identity','balance','orders']){const f=fixture();if(variant==='identity')f.state.accountId='different-account';if(variant==='balance'){const original=f.broker.account;f.broker.account=async()=>({...await original(),equity:'100000'});}if(variant==='orders')f.broker.orders=async()=>[{symbol:'SPY',side:'buy'}];await assert.rejects(paperStep(f));assert.equal(f.posts(),0);}});
test('loss halt persists and can exit after an earlier same-day action',async()=>{const f=fixture();await paperStep({...f,enabled:false});const day=Object.values(f.state.days)[0];day.acted=true;const original=f.broker.account;f.broker.account=async()=>({...await original(),equity:'97'});f.broker.positions=async()=>[{symbol:'SPY',side:'long',qty:'.05',qty_available:'.05',market_value:'5'}];await paperStep(f);assert.equal(day.halted,true);assert.equal(day.riskExited,true);assert.equal(f.state.pending.side,'sell');assert.equal(f.posts(),1);});
test('loss halt without holdings prevents entries and survives another run',async()=>{const f=fixture();await paperStep({...f,enabled:false});const original=f.broker.account;f.broker.account=async()=>({...await original(),equity:'97'});await paperStep(f);await paperStep(f);assert.equal(f.posts(),0);assert.equal(Object.values(f.state.days)[0].halted,true);});
test('stale daily history and journal write failure cannot submit',async()=>{const f=fixture();const b=await f.broker.bars();b.at(-1).date='2026-08-01';await assert.rejects(paperStep(f));assert.equal(f.posts(),0);const second=fixture();await assert.rejects(paperStep({...second,save:async()=>{throw Error('Disk full');}}),/Disk full/);assert.equal(second.posts(),0);});
test('changed strategy configuration cannot reuse an existing session journal',async()=>{const f=fixture();await paperStep({...f,enabled:false});await assert.rejects(paperStep({...f,strategy:'momentum'}),/Configuration changed/);assert.equal(f.posts(),0);});
test('second local process cannot proceed through an existing exclusive lock',async()=>{const {mkdtemp,writeFile,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const {spawnSync}=await import('node:child_process');const dir=await mkdtemp(join(tmpdir(),'sterling-lock-test-'));try{await writeFile(join(dir,'runner.lock'),'test-owner');const r=spawnSync(process.execPath,['scripts/paper-runner.mjs','--once'],{cwd:new URL('..',import.meta.url),env:{...process.env,APCA_API_KEY_ID:'test',APCA_API_SECRET_KEY:'test',PAPER_STATE_DIR:dir},encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/Runner lock exists/);}finally{await rm(dir,{recursive:true,force:true});}});
