'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { Library,BrokerPanel,Methodology } from './panels';
import { CloudPanel } from './cloud-panel';
import { researchTool } from '@/lib/web-tools';
import { ArrowUpRight, FlaskConical, Play, ShieldCheck, Upload, Download, Activity, Layers, Landmark, BookOpen, Cloud } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Table,TableHeader,TableRow,TableHead,TableBody,TableCell } from '@/components/ui/table';
import { backtest,strategies,demoBars,defaultConfig,parseCSV,barsToCSV,validateConfig } from '@/lib/engine.mjs';
type ExperimentResponse = {message?:string;experiments:SavedExperiment[];experiment:SavedExperiment & {bars:ReturnType<typeof demoBars>}};
type SavedExperiment = {id:string;at:string;data:string;phase:string;rule:string;equity:number;currency:string;config:typeof defaultConfig;hasData?:boolean;synthetic?:boolean};
export default function Home(){
 const [datasetSynthetic,setDatasetSynthetic]=useState(true);const [regime,setRegime]=useState('mixed');const [active,setActive]=useState('trend');const [config,setConfig]=useState(defaultConfig);
 const [draft,setDraft]=useState({capital:'100',allocation:'25',costBps:'10',fee:'0',drawdownStop:'10',currency:'GBP'});
 const [phase,setPhase]=useState('research');const [holdoutSeen,setHoldoutSeen]=useState(false);const [imported,setImported]=useState<ReturnType<typeof demoBars>|null>(null);const [dataName,setDataName]=useState('Synthetic · mixed market');const [dataCurrency,setDataCurrency]=useState('GBP');const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState<SavedExperiment[]>([]);const [legacy,setLegacy]=useState<SavedExperiment[]>([]);const [saving,setSaving]=useState(false);const [journalError,setJournalError]=useState('');const saveId=useRef<string|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 const bars=useMemo(()=>imported??demoBars(regime),[imported,regime]);const results=useMemo(()=>strategies.map(s=>backtest(bars,s.id,config,phase)),[bars,config,phase]);const selected=results.find(r=>r.id===active)!;
 const money=(v:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:config.currency}).format(v);
 async function refreshJournal(){try{const response=await fetch('/api/experiments',{cache:'no-store'});const body=await response.json() as ExperimentResponse;if(!response.ok)throw Error(body.message);setSaved(body.experiments);setJournalError('');}catch(e){setJournalError(e instanceof Error?e.message:'Could not load cloud research.');}}
 useEffect(()=>{void refreshJournal();try{const previous=JSON.parse(localStorage.getItem('sterling-research-journal')??'[]');if(Array.isArray(previous))setLegacy(previous.filter(r=>r&&typeof r.at==='string'&&typeof r.data==='string'&&Number.isFinite(r.equity)).slice(-30));}catch{}},[]);
 useEffect(()=>{saveId.current=null;},[bars,config,phase,active,dataName]);
 async function saveExperiment(){setSaving(true);try{saveId.current??=crypto.randomUUID();const response=await fetch('/api/experiments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:saveId.current,data:dataName,phase,rule:active,currency:config.currency,config,bars,synthetic:datasetSynthetic})});const body=await response.json() as ExperimentResponse;if(!response.ok)throw Error(body.message);saveId.current=null;setMessage('Full experiment saved to your private cloud journal.');setError('');await refreshJournal();}catch(e){setError(e instanceof Error?e.message:'Cloud save failed. Export the experiment to keep a copy.');}finally{setSaving(false);}}
 async function importLegacy(){setSaving(true);try{for(const record of legacy){const key=JSON.stringify([record.at,record.data,record.rule,record.phase,record.equity]);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key));const id='legacy-'+Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('');const response=await fetch('/api/experiments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...record,id,legacy:true})});if(!response.ok){const body=await response.json() as ExperimentResponse;throw Error(body.message);}}setLegacy([]);setMessage('Browser summaries copied to your cloud journal. Their original prices were not stored by the old journal.');await refreshJournal();}catch(e){setError(e instanceof Error?e.message:'Import failed. Original browser records have been preserved.');}finally{setSaving(false);}}
 async function restoreExperiment(id:string){setSaving(true);try{const response=await fetch('/api/experiments?id='+encodeURIComponent(id),{cache:'no-store'});const body=await response.json() as ExperimentResponse;if(!response.ok)throw Error(body.message);const r=body.experiment;if(!r.bars)throw Error('This old summary has no stored prices.');setDatasetSynthetic(r.synthetic===true);setImported(r.bars);setDataName(r.data);setDataCurrency(r.currency);setConfig(r.config);setDraft(Object.fromEntries(Object.entries(r.config).map(([k,v])=>[k,String(v)])) as typeof draft);setActive(r.rule);setPhase(r.phase);setHoldoutSeen(r.phase==='holdout');setError('');setMessage('Saved prices and settings restored from the cloud.');}catch(e){setError(e instanceof Error?e.message:'Could not restore experiment.');}finally{setSaving(false);}}
 const toolRun=useRef((id:string)=>({}));toolRun.current=(id:string)=>{const r=backtest(bars,id,config,phase);flushSync(()=>setActive(id));return {strategy:id,dataset:dataName,phase,currency:config.currency,equity:r.finalEquity,returnPct:r.returnPct,drawdown:r.maxDrawdown,orders:r.trades.length,simulated:true};};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:ReturnType<typeof researchTool>,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool(researchTool(id=>toolRun.current(id)),{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[]);
 function updateDraft(key:string,value:string){setDraft(d=>({...d,[key]:value}));}
 function run(){try{const c=validateConfig({...config,...Object.fromEntries(Object.entries(draft).map(([k,v])=>[k,k==='currency'?v:Number(v)]))});if(imported&&c.currency!==dataCurrency)throw Error('Use the currency declared when loading these prices. Changing currency does not convert prices. Re-import to correct a declaration.');setConfig(c);setError('');setMessage('Comparison updated with your assumptions.');}catch(e){setError(e instanceof Error?e.message:'Check your assumptions.');}}
 function changeRegime(v:string|null){if(!v)return;setRegime(v);setDatasetSynthetic(true);setImported(null);setDataName('Synthetic · '+v+' market');setDataCurrency('GBP');setPhase('research');setHoldoutSeen(false);setConfig(c=>({...c,currency:'GBP'}));setDraft(d=>({...d,currency:'GBP'}));setError('');}
 function download(name:string,text:string,type='text/csv'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 async function importFile(file:File){try{if(file.size>2000000)throw Error('CSV must be smaller than 2 MB.');const loaded=parseCSV(await file.text());setDatasetSynthetic(false);setImported(loaded);setDataName(file.name);setDataCurrency(draft.currency);setConfig(c=>({...c,currency:draft.currency}));setPhase('research');setHoldoutSeen(false);setError('');setMessage('Imported '+loaded.length+' daily rows in '+draft.currency+'. Check the source and adjustment method.');}catch(e){setError(e instanceof Error?e.message:'Could not import CSV.');}}
 async function loadBroker(){setBusy(true);try{const res=await fetch('/api/broker?symbol=SPY',{cache:'no-store'});const d=await res.json() as {bars?:ReturnType<typeof demoBars>;message?:string};if(!res.ok||!d.bars)throw Error(d.message??'Connect an Alpaca paper account first.');const loaded=parseCSV(barsToCSV(d.bars));setDatasetSynthetic(false);setImported(loaded);setDataName('SPY · Alpaca IEX · adjusted');setDataCurrency('USD');setConfig(c=>({...c,currency:'USD'}));setDraft(d=>({...d,currency:'USD'}));setPhase('research');setHoldoutSeen(false);setError('');setMessage('Loaded completed daily IEX bars in USD. This is one exchange, not consolidated market data.');}catch(e){setError(e instanceof Error?e.message:'Could not load broker history.');}finally{setBusy(false);}}
 function exportResults(){download('sterling-experiment.json',JSON.stringify({createdAt:new Date().toISOString(),data:dataName,dataCurrency,synthetic:datasetSynthetic,phase,config,results,bars,limitations:'Hypothetical daily-bar research; costs are assumed; no guaranteed returns.'},null,2),'application/json');}
 const all=results.flatMap(r=>r.curve.map(p=>p.equity)),lo=Math.min(...all)*.98,hi=Math.max(...all)*1.02;const path=(r:typeof selected)=>r.curve.map((p,i)=>`${i?'L':'M'}${20+i/(r.curve.length-1)*880},${240-(p.equity-lo)/(hi-lo)*210}`).join(' ');
 return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={23}/></span>STERLING<span className="brand-divider"/> <small>TRADING LAB</small></div><span className="badge"><span className="status-dot"/> Research & paper only</span></header>
 <Tabs defaultValue="cloud" className="workspace"><TabsList className="navigation" variant="line"><TabsTrigger value="cloud"><Cloud/>Cloud portfolio</TabsTrigger><TabsTrigger value="lab"><FlaskConical/>Strategy workspace</TabsTrigger><TabsTrigger value="library"><Layers/>Strategy library</TabsTrigger><TabsTrigger value="broker"><Landmark/>Paper trading</TabsTrigger><TabsTrigger value="notes"><BookOpen/>Methodology</TabsTrigger></TabsList>
 <TabsContent value="cloud"><CloudPanel/></TabsContent>
 <TabsContent value="lab"><div className="page-heading"><div><p className="eyebrow">TEST FIRST. TRADE WITH EVIDENCE.</p><h1>Strategy workspace<span>.</span></h1><p className="muted">Compare clear rules. Understand the risk before putting money behind them.</p></div><span className="capsule"><FlaskConical size={16}/>{datasetSynthetic?"Synthetic demonstration":"Imported daily data"}</span></div>
 <div className="notice"><ShieldCheck size={20}/><p>£100 → £1,000,000 in 30 days needs <strong>35.94% growth every day</strong>. That is not a reliable trading plan. This lab makes no return promises.</p></div>
 <div className="data-toolbar"><div><span className="data-label">DATASET</span><strong>{dataName}</strong><span className="muted">{bars.length} sessions · {config.currency}</span></div><div className="toolbar-actions"><Button variant="outline" onClick={()=>fileRef.current?.click()}><Upload size={16}/> Import CSV</Button><Button variant="outline" onClick={loadBroker} disabled={busy}>{busy?'Loading…':'Load SPY from broker'}</Button><Button variant="outline" onClick={exportResults}><Download size={16}/> Export</Button></div><input ref={fileRef} type="file" accept=".csv,text/csv" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='';}}/></div>
 <details className="import-help"><summary>CSV format & currency</summary><p>Use <code>date,open,high,low,close</code>, ascending YYYY-MM-DD dates, 180–10,000 daily rows, and consistently adjusted positive prices. Choose the price currency in the settings before importing. The app cannot verify vendor provenance or adjust corporate actions for you.</p><Button variant="link" onClick={()=>download('sterling-synthetic-example.csv',barsToCSV(demoBars()))}>Download synthetic example CSV</Button></details>
 {error&&<p role="alert" className="error-message">{error}</p>}{message&&<p role="status" className="success-message">{message}</p>}
 <div className="phase-bar"><div><Button variant={phase==='research'?'secondary':'ghost'} onClick={()=>setPhase('research')}>Research · first 70%</Button><Button variant={phase==='holdout'?'secondary':'ghost'} onClick={()=>{setPhase('holdout');setHoldoutSeen(true);}}>Evaluate final 30%</Button></div><span>{holdoutSeen?'Holdout has been viewed. Further tuning is exploratory.':'Final 30% held back from the initial comparison.'}</span></div>
 <div className="lab-grid"><section className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">HYPOTHETICAL EQUITY</p><h2>{strategies.find(s=>s.id===active)?.name}</h2></div><Select value={regime} onValueChange={changeRegime}><SelectTrigger aria-label="Load a synthetic demonstration market"><SelectValue>{regime==='mixed'?'Mixed market':regime==='trend'?'Trending market':'Stress scenario'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="mixed">Mixed market</SelectItem><SelectItem value="trend">Trending market</SelectItem><SelectItem value="stress">Stress scenario</SelectItem></SelectContent></Select></div>
 <div className="metric-row"><div><span>Ending equity</span><strong>{money(selected.finalEquity)}</strong></div><div><span>Total return</span><strong className={selected.returnPct>=0?'positive':'negative'}>{selected.returnPct.toFixed(2)}%</strong></div><div><span>Maximum drawdown</span><strong>{selected.maxDrawdown.toFixed(2)}%</strong></div></div>
 <svg className="equity-chart" viewBox="0 0 940 275" role="img" aria-label="Hypothetical equity of the chosen strategy compared with buy and hold"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c2ef78" stopOpacity=".17"/><stop offset="100%" stopColor="#c2ef78" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(v=><g key={v}><line x1="20" x2="900" y1={30+v*70} y2={30+v*70} stroke="#293135" strokeDasharray="3 5"/><text x="905" y={35+v*70} fill="#869591" fontSize="12">{(hi-v/3*(hi-lo)).toFixed(0)}</text></g>)}<path d={path(selected)+' L900,255 L20,255 Z'} fill="url(#fill)"/><path d={path(results[0])} fill="none" stroke="#7284a0" strokeWidth="2" strokeDasharray="5 6"/><path d={path(selected)} fill="none" stroke="#c2ef78" strokeWidth="2.5"/></svg><div className="chart-footer"><span><i className="legend lime"/>Selected strategy <i className="legend blue"/>Buy & hold</span><span>{selected.start} — {selected.end}</span></div><p className="footnote">{datasetSynthetic?"Synthetic prices":"Imported prices"} · {phase==='holdout'?"Final 30% evaluation":"First 70% research"} · Fractional positions · Open ending positions marked at the final close.</p></section>
 <aside className="panel controls"><p className="eyebrow">EXPERIMENT SETTINGS</p><h2>Start small. Measure.</h2><label>Starting balance ({draft.currency})<Input type="number" min="1" max="100000000" value={draft.capital} onChange={e=>updateDraft('capital',e.target.value)}/></label>
 <div className="settings-grid"><label>Price currency<Select value={draft.currency} onValueChange={v=>v&&updateDraft('currency',v)}><SelectTrigger aria-label="Price currency"><SelectValue/></SelectTrigger><SelectContent>{['GBP','USD','EUR'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label>Allocation (%)<Input type="number" min="1" max="100" value={draft.allocation} onChange={e=>updateDraft('allocation',e.target.value)}/></label><label>Cost per side (bps)<Input type="number" min="0" max="500" value={draft.costBps} onChange={e=>updateDraft('costBps',e.target.value)}/></label><label>Fee per order<Input type="number" min="0" max="100" step=".01" value={draft.fee} onChange={e=>updateDraft('fee',e.target.value)}/></label><label>Drawdown stop (%)<Input type="number" min="1" max="100" value={draft.drawdownStop} onChange={e=>updateDraft('drawdownStop',e.target.value)}/></label></div>
 <Button className="run-button" onClick={run}><Play size={16}/> Run comparison</Button><p className="footnote">10 basis points = 0.10% per side. Unleveraged, long-only. Changes apply when you run the comparison.</p><div className="risk-note"><ShieldCheck size={20}/><span>Simulated fills<br/><small>No money used in these tests.</small></span></div></aside></div>
 <section className="panel comparison"><div className="panel-head"><div><p className="eyebrow">FIVE TRANSPARENT BASELINES</p><h2>Compare the evidence</h2></div><span className="muted">Select a rule to inspect</span></div><Table><TableHeader><TableRow><TableHead>Strategy</TableHead><TableHead>Return</TableHead><TableHead>Drawdown</TableHead><TableHead>Orders</TableHead><TableHead>Costs</TableHead></TableRow></TableHeader><TableBody>{results.map((r,i)=><TableRow key={r.id} className={active===r.id?'selected-row':''}><TableCell><button className="strategy-name" onClick={()=>setActive(r.id)}><span className="strategy-index">0{i+1}</span><span>{strategies[i].name}<small>{strategies[i].family}</small></span><ArrowUpRight size={16}/></button></TableCell><TableCell className={r.returnPct>=0?'positive':'negative'}>{r.returnPct.toFixed(2)}%</TableCell><TableCell>{r.maxDrawdown.toFixed(2)}%</TableCell><TableCell>{r.trades.length}</TableCell><TableCell>{money(r.totalCosts)}</TableCell></TableRow>)}</TableBody></Table></section>
 <section className="panel trade-panel"><div className="panel-head"><div><p className="eyebrow">INSPECT THE RULE</p><h2>{strategies.find(s=>s.id===active)?.name}</h2></div><Button variant="outline" disabled={saving} onClick={saveExperiment}>{saving?'Saving…':'Save to cloud'}</Button></div><p className="muted">{strategies.find(s=>s.id===active)?.rule}</p><div className="trade-summary"><span>{selected.closed} closed trades · Win rate {selected.winRate===null?'not available':selected.winRate.toFixed(1)+'%'}</span><span>{selected.openPosition?'Position remains open':'No ending position'} · {selected.halted?'Drawdown stop triggered':'Drawdown stop not triggered'}</span></div>{selected.pendingStop&&<p className="error-message">Stop triggered at the final close. Its next-open exit is outside this evaluation.</p>}<details className="trade-details"><summary>View {selected.trades.length} simulated orders</summary><div className="trade-scroll"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Action</TableHead><TableHead>Fill price</TableHead><TableHead>Quantity</TableHead><TableHead>Reason</TableHead></TableRow></TableHeader><TableBody>{selected.trades.map((t,i)=><TableRow key={i}><TableCell>{t.date}</TableCell><TableCell>{t.side}</TableCell><TableCell>{money(t.price)}</TableCell><TableCell>{t.qty.toFixed(6)}</TableCell><TableCell>{t.reason}</TableCell></TableRow>)}</TableBody></Table>{!selected.trades.length&&<p className="empty-message">No qualifying orders in this evaluation.</p>}</div></details></section>
 <section className="panel trade-panel"><div className="panel-head"><div><p className="eyebrow">PRIVATE CLOUD JOURNAL</p><h2>Saved experiments</h2></div><Button variant="outline" disabled={!saved.length} onClick={()=>download('sterling-journal.json',JSON.stringify(saved,null,2),'application/json')}>Export journal</Button></div><p className="footnote">Saved across your devices. New saves include prices, settings and simulated results. Older imported summaries may have no stored prices.</p>{journalError&&<p role="alert" className="error-message">{journalError} <button onClick={refreshJournal}>Retry</button></p>}{legacy.length>0&&<Button variant="outline" disabled={saving} onClick={importLegacy}>Import {legacy.length} browser summaries</Button>}{saved.length?<div className="journal-list">{saved.map((r,i)=><div key={r.at+i}><span>{strategies.find(s=>s.id===r.rule)?.name??r.rule}<small>{r.data} · {r.phase} · {r.at.slice(0,10)}</small></span><strong>{new Intl.NumberFormat('en-GB',{style:'currency',currency:r.currency}).format(r.equity)}</strong>{r.hasData&&<Button variant="outline" disabled={saving} onClick={()=>restoreExperiment(r.id)}>Open</Button>}</div>)}</div>:<p className="empty-message">No saved experiments yet. Save a result after inspecting its orders.</p>}</section>
 </TabsContent>
 <TabsContent value="library"><Library/></TabsContent><TabsContent value="broker"><BrokerPanel/></TabsContent><TabsContent value="notes"><Methodology/></TabsContent>
 </Tabs><footer className="footer"><span>STERLING / A place to test your conviction.</span><span>Research is not a promise of future returns.</span></footer></main>;
}
